import datetime
from enum import Enum

class ProcessStatus(Enum):
    AVAILABLE = 'AVAILABLE'
    PROCESSING = 'PROCESSING'
    SLEEP = 'SLEEP'


class Constants:
    REPORT_START_DATE = datetime.date(2019, 1, 1)
    REPORT_END_DATE = datetime.date(2023, 12, 31)

    ENROLL_BATCH_SIZE = 1000
    ENROLL_MAX_PAGE_SIZE = 412
    ENROLL_RUNNING_PAGE = 0
    ENROLL_PROCESS_STATUS = ProcessStatus.AVAILABLE

    DEPENDENT_BATCH_SIZE = 100
    DEPENDENT_MAX_PAGE_SIZE = 1080
    DEPENDENT_RUNNING_PAGE = 0
    DEPENDENT_PROCESS_STATUS = ProcessStatus.AVAILABLE

    ENROLL_PRODUCT_BATCH_SIZE = 10000
    ENROLL_PRODUCT_MAX_PAGE_SIZE = 2
    ENROLL_PRODUCT_RUNNING_PAGE = 2
    ENROLL_PRODUCT_PROCESS_STATUS = ProcessStatus.AVAILABLE

    DEPENDENT_PRODUCT_BATCH_SIZE = 1000
    DEPENDENT_PRODUCT_MAX_PAGE_SIZE = 30
    DEPENDENT_PRODUCT_RUNNING_PAGE = 0
    DEPENDENT_PRODUCT_PROCESS_STATUS = ProcessStatus.AVAILABLE
