# Generated by Django 5.0.1 on 2024-01-19 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentqueue',
            name='claim_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
