# Generated by Django 5.0.1 on 2024-01-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_paymentqueue_claim_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnalaysisReportClaimForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('group_policy', models.IntegerField(default=0)),
                ('group_policy_cluster', models.IntegerField(default=0)),
                ('group_policy_product', models.IntegerField(default=0)),
                ('group_policy_cluster_product', models.IntegerField(default=0)),
                ('enroll', models.IntegerField(default=0)),
                ('enroll_product', models.IntegerField(default=0)),
                ('dependent', models.IntegerField(default=0)),
                ('dependent_product', models.IntegerField(default=0)),
                ('claim_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
