# Generated by Django 5.0.1 on 2024-01-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0003_dataanalaysisreportclaimforecast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppolicyinactivecycle',
            old_name='group_policy_id',
            new_name='parent_id',
        ),
    ]
