# Generated by Django 5.0.1 on 2024-01-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0004_rename_group_policy_id_grouppolicyinactivecycle_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataanalaysisreportclaimforecast',
            old_name='group_policy',
            new_name='group_policy_active_weight',
        ),
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='group_policy_inactive_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='group_policy_total_weight',
            field=models.IntegerField(default=0),
        ),
    ]
