# Generated by Django 5.0.1 on 2024-01-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0005_rename_group_policy_dataanalaysisreportclaimforecast_group_policy_active_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataanalaysisreportclaimforecast',
            name='group_policy_total_weight',
        ),
    ]
