# Generated by Django 5.0.1 on 2024-01-27 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0006_remove_dataanalaysisreportclaimforecast_group_policy_total_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataanalaysisreportclaimforecast',
            name='group_policy_active_weight',
        ),
        migrations.RemoveField(
            model_name='dataanalaysisreportclaimforecast',
            name='group_policy_inactive_weight',
        ),
        migrations.RemoveField(
            model_name='dataanalaysisreportclaimforecast',
            name='month',
        ),
        migrations.RemoveField(
            model_name='dataanalaysisreportclaimforecast',
            name='year',
        ),
    ]
