# Generated by Django 5.0.1 on 2024-01-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0007_remove_dataanalaysisreportclaimforecast_group_policy_active_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='group_policy_active_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='group_policy_inactive_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
