# Generated by Django 5.0.1 on 2024-01-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0009_dataanalaysisreportclaimforecast_group_policy_total_active_at_least_one_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataanalaysisreportclaimforecast',
            old_name='group_policy_total_active_at_least_one_day',
            new_name='group_policy_active_at_least_one_day',
        ),
    ]
