# Generated by Django 5.0.1 on 2024-01-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0010_rename_group_policy_total_active_at_least_one_day_dataanalaysisreportclaimforecast_group_policy_acti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollinactivecycle',
            old_name='enroll_id',
            new_name='parent_id',
        ),
        migrations.RemoveField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll',
        ),
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll_active_at_least_one_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll_active_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll_inactive_weight',
            field=models.IntegerField(default=0),
        ),
    ]
