# Generated by Django 5.0.1 on 2024-01-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0011_rename_enroll_id_enrollinactivecycle_parent_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppolicyclusterproductinactivecycle',
            old_name='group_policy_cluster_product_id',
            new_name='parent_id',
        ),
    ]
