# Generated by Django 5.0.1 on 2024-01-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0013_remove_dataanalaysisreportclaimforecast_group_policy_cluster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppolicyclusterinactivecycle',
            old_name='group_policy_cluster_id',
            new_name='parent_id',
        ),
    ]
