# Generated by Django 5.0.1 on 2024-01-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0014_rename_group_policy_cluster_id_grouppolicyclusterinactivecycle_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll_active_mid_age_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll_active_old_age_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll_active_young_age_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll_inactive_mid_age_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll_inactive_old_age_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll_inactive_young_age_weight',
            field=models.IntegerField(default=0),
        ),
    ]
