# Generated by Django 5.0.1 on 2024-01-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0015_dataanalaysisreportclaimforecast_enroll_active_mid_age_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll_active_child_age_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll_inactive_child_age_weight',
            field=models.IntegerField(default=0),
        ),
    ]
