# Generated by Django 5.0.1 on 2024-02-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0017_rename_dependent_product_id_dependentproductinactivecycle_parent_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppolicyproductinactivecycle',
            old_name='group_policy_product_id',
            new_name='parent_id',
        ),
        migrations.RemoveField(
            model_name='dataanalaysisreportclaimforecast',
            name='dependent_product_ID_active_weight',
        ),
        migrations.RemoveField(
            model_name='dataanalaysisreportclaimforecast',
            name='dependent_product_ID_inactive_weight',
        ),
        migrations.RemoveField(
            model_name='dataanalaysisreportclaimforecast',
            name='dependent_product_IL_active_weight',
        ),
        migrations.RemoveField(
            model_name='dataanalaysisreportclaimforecast',
            name='dependent_product_IL_inactive_weight',
        ),
        migrations.RemoveField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll_product_ID_active_weight',
        ),
        migrations.RemoveField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll_product_ID_inactive_weight',
        ),
        migrations.RemoveField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll_product_IL_active_weight',
        ),
        migrations.RemoveField(
            model_name='dataanalaysisreportclaimforecast',
            name='enroll_product_IL_inactive_weight',
        ),
    ]
